# Generated by Django 5.2.13 on 2026-04-29 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_seed_source_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('url', models.URLField(max_length=500, unique=True, verbose_name='URL do feed RSS')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='feeds.sourcecategory', verbose_name='categoria')),
                ('active', models.BooleanField(default=True, verbose_name='ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'Fonte RSS',
                'verbose_name_plural': 'Fontes RSS',
                'ordering': ['name'],
            },
        ),
    ]
