# Generated by Django 5.x on 2026-05-01 00:00
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_create_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nome')),
                ('color', models.CharField(choices=[
                    ('blue', 'Azul'),
                    ('green', 'Verde'),
                    ('red', 'Vermelho'),
                    ('yellow', 'Amarelo'),
                    ('purple', 'Roxo'),
                    ('pink', 'Rosa'),
                    ('orange', 'Laranja'),
                    ('gray', 'Cinza'),
                ], default='blue', max_length=20, verbose_name='cor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
    ]
