# Generated by Django 5.2.13 on 2026-05-12 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_seed_default_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='título')),
                ('summary', models.TextField(blank=True, verbose_name='resumo')),
                ('link', models.URLField(max_length=1000, verbose_name='link original')),
                ('external_id', models.CharField(blank=True, max_length=500, verbose_name='identificador externo')),
                ('dedupe_key', models.CharField(max_length=64, verbose_name='chave de deduplicação')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publicado em')),
                ('is_read', models.BooleanField(default=False, verbose_name='lido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to='feeds.source', verbose_name='fonte')),
            ],
            options={
                'verbose_name': 'Informativo',
                'verbose_name_plural': 'Informativos',
                'ordering': ['-created_at'],
                'constraints': [
                    models.UniqueConstraint(fields=('source', 'dedupe_key'), name='unique_news_item_per_source_dedupe'),
                ],
            },
        ),
    ]
