# Generated by Django 5.2.13 on 2026-05-18 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0006_create_news_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItemAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, verbose_name='resumo da IA')),
                ('impact_level', models.CharField(blank=True, choices=[('high', 'Alta'), ('medium', 'Média'), ('low', 'Baixa')], max_length=16, verbose_name='grau de impacto')),
                ('impact_context', models.CharField(blank=True, max_length=255, verbose_name='contexto do impacto')),
                ('keywords', models.JSONField(blank=True, default=list, verbose_name='palavras-chave')),
                ('importance_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='score de importância')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='data de vigência')),
                ('effective_date_label', models.CharField(blank=True, max_length=120, verbose_name='rótulo da vigência')),
                ('status', models.CharField(choices=[('completed', 'Concluída'), ('failed', 'Falhou')], default='failed', max_length=16, verbose_name='status da análise')),
                ('provider', models.CharField(blank=True, max_length=50, verbose_name='provider')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='modelo')),
                ('input_hash', models.CharField(blank=True, max_length=64, verbose_name='hash de entrada')),
                ('pipeline_version', models.CharField(blank=True, max_length=50, verbose_name='versão do pipeline')),
                ('error_message', models.CharField(blank=True, max_length=255, verbose_name='mensagem de erro')),
                ('analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='analisado em')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='última tentativa em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('news_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='feeds.newsitem', verbose_name='informativo')),
            ],
            options={
                'verbose_name': 'Análise de Informativo',
                'verbose_name_plural': 'Análises de Informativos',
            },
        ),
    ]
