# Generated by Django 5.2.13 on 2026-05-18 00:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_create_news_item_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Em andamento'), ('completed', 'Concluída'), ('failed', 'Falhou')], default='pending', max_length=16, verbose_name='status')),
                ('current_stage', models.CharField(choices=[('queued', 'Na fila'), ('rss', 'Importação RSS'), ('analysis', 'Análise por IA'), ('completed', 'Concluída'), ('failed', 'Falhou')], default='queued', max_length=16, verbose_name='etapa atual')),
                ('stage_title', models.CharField(blank=True, max_length=120, verbose_name='título da etapa')),
                ('stage_message', models.CharField(blank=True, max_length=255, verbose_name='mensagem da etapa')),
                ('rss_total_sources', models.PositiveIntegerField(default=0, verbose_name='total de fontes RSS')),
                ('rss_processed_sources', models.PositiveIntegerField(default=0, verbose_name='fontes RSS processadas')),
                ('analysis_enabled', models.BooleanField(default=False, verbose_name='análise por IA habilitada')),
                ('analysis_total_items', models.PositiveIntegerField(default=0, verbose_name='total de notícias para IA')),
                ('analysis_processed_items', models.PositiveIntegerField(default=0, verbose_name='notícias analisadas pela IA')),
                ('imported_created_count', models.PositiveIntegerField(default=0, verbose_name='notícias novas importadas')),
                ('imported_existing_count', models.PositiveIntegerField(default=0, verbose_name='notícias já existentes')),
                ('import_error_count', models.PositiveIntegerField(default=0, verbose_name='fontes com erro')),
                ('import_skipped_count', models.PositiveIntegerField(default=0, verbose_name='notícias ignoradas na importação')),
                ('analysis_failure_count', models.PositiveIntegerField(default=0, verbose_name='falhas de análise IA')),
                ('analysis_skipped_count', models.PositiveIntegerField(default=0, verbose_name='notícias sem análise IA')),
                ('redirect_query', models.CharField(blank=True, max_length=255, verbose_name='filtro de pesquisa')),
                ('redirect_source', models.CharField(blank=True, max_length=20, verbose_name='filtro de fonte')),
                ('redirect_status', models.CharField(blank=True, max_length=20, verbose_name='filtro de status')),
                ('result_messages', models.JSONField(blank=True, default=list, verbose_name='mensagens finais')),
                ('error_message', models.CharField(blank=True, max_length=255, verbose_name='mensagem de erro')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='iniciado em')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finalizado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'Job de Atualização de Informativos',
                'verbose_name_plural': 'Jobs de Atualização de Informativos',
                'ordering': ['-created_at'],
            },
        ),
    ]
